export const SHOW_LOADER = 'SHOW_LOADER';

export const HIDE_LOADER = 'HIDE_LOADER';

export const GROUP_SEARCH_INTERCEPTOR = 'GROUP_SEARCH_INTERCEPTOR';

export const GROUP_SEARCH = 'GROUP_SEARCH';

export const GROUP_SEARCH_RESULT = 'GROUP_SEARCH_RESULT';

export const GROUP_SEARCH_RESULT_INTERCEPTOR = 'GROUP_SEARCH_RESULT_INTERCEPTOR';

export const CHANGE_GROUP_SEARCH_PG_NO = 'CHANGE_GROUP_SEARCH_PG_NO';

export const CHANGE_GROUP_SEARCH_PG_NO_INTERCEPTOR = 'CHANGE_GROUP_SEARCH_PG_NO_INTERCEPTOR';

export const SELECT_GROUP_ID = 'SELECT_GROUP_ID';

export const GET_GROUP_IMAGES = 'GET_GROUP_IMAGES';

export const GET_GROUP_IMAGES_INTERCEPTOR = 'GET_GROUP_IMAGES_INTERCEPTOR';

export const GET_GROUP_ALL_IMAGES = 'GET_GROUP_ALL_IMAGES';

export const GET_GROUP_ALL_IMAGES_INTERCEPTOR = 'GET_GROUP_ALL_IMAGES_INTERCEPTOR';

export const SET_UP_GAME = 'SET_UP_GAME';

export const CHANGE_BOARD_DIMENSION = 'CHANGE_BOARD_DIMENSION';
